version: "3.7"

services:
  database:
    image: postgres:15.2
    restart: on-failure
    environment:
      POSTGRES_MULTIPLE_DATABASES: kratos,keto,hydra
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: dbuser
    volumes:
        - ./configs/postgresql/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
        - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      intranet: null

  kratos-migrate:
    depends_on:
      - database 
    image: oryd/kratos:v0.13.0
    restart: on-failure
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    environment:
      DSN: postgres://dbuser:dbpassword@database:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - kratos-config:/etc/config/kratos
    networks:
      intranet: null

  keto-migrate:
    depends_on:
      - database  
    image: oryd/keto:v0.11.1
    restart: on-failure
    command: migrate up -y
    environment:
      DSN: postgres://dbuser:dbpassword@database:5432/keto?sslmode=disable
      LOG_LEVEL: debug
    links:
      - database:database
    volumes:
      - keto-config:/home/ory
    networks:
      intranet: null

  hydra-migrate:
    depends_on:
        - database  
    image: oryd/hydra:v2.1.1
    restart: on-failure
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    environment:
      DSN: postgres://dbuser:dbpassword@database:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - hydra-config:/etc/config/hydra
    networks:
      intranet: null

  hydra:
    depends_on:
      hydra-migrate:
        condition: service_started
      jaeger:
        condition: service_started
    image: oryd/hydra:v2.1.1
    restart: unless-stopped
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    environment:
      DSN: postgres://dbuser:dbpassword@database:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      TRACING_PROVIDER: jaeger
      TRACING_SERVICE_NAME: Hydra
      TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS: jaeger:6831
      TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL: http://jaeger:5778/sampling
      TRACING_PROVIDERS_JAEGER_SAMPLING_TRACE_ID_RATIO: "1"
    volumes:
      - hydra-config:/etc/config/hydra
    ports:
    - "4444:4444"
    - "4445:4445"
    - "5555:5555"
    networks:
      intranet: null

  keto:
    depends_on:
      jaeger:
        condition: service_started
      keto-migrate:
        condition: service_started
    image: oryd/keto:v0.11.1
    restart: on-failure
    command: serve -c /home/ory/keto.yml
    environment:
      DSN: postgres://dbuser:dbpassword@database:5432/keto?sslmode=disable
      TRACING_PROVIDER: jaeger
      TRACING_SERVICE_NAME: Keto
      TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS: jaeger:6831
      TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL: http://jaeger:5778/sampling
    links:
    - database:database
    volumes:
      - keto-config:/home/ory
    ports:
    - "4466:4466"
    - "4467:4467"
    networks:
      intranet: null

  kratos:
    depends_on:
      jaeger:
        condition: service_started
      kratos-migrate:
        condition: service_started
    image: oryd/kratos:v0.13.0
    restart: unless-stopped
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    environment:
      DSN: postgres://dbuser:dbpassword@database:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      LOG_LEVEL: trace
      SERVE_PUBLIC_BASE_URL: http://127.0.0.1:4455/.ory/kratos/public/
      TRACING_PROVIDER: jaeger
      TRACING_SERVICE_NAME: Kratos
      TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS: jaeger:6831
      TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL: http://jaeger:5778/sampling
    volumes:
      - kratos-config:/etc/config/kratos
    ports:
    - "4433:4433"
    - "4434:4434"
    networks:
      intranet: null

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.13.0
    restart: on-failure
    environment:
      JWKS_URL: http://oathkeeper:4456/.well-known/jwks.json
      KRATOS_BROWSER_URL: http://127.0.0.1:4455/.ory/kratos/public
      KRATOS_PUBLIC_URL: http://kratos:4433/
      PORT: '4435'
      SECURITY_MODE: jwks
    networks:
      intranet: null

  oathkeeper:
    depends_on:
      kratos:
        condition: service_started
    image: oryd/oathkeeper:v0.40.2
    restart: on-failure
    command: serve proxy -c /etc/config/oathkeeper/oathkeeper.yml
    environment:
      LOG_LEVEL: debug
      LOG_LEAK_SENSITIVE_VALUES: "true"
      TRACING_PROVIDER: jaeger
      TRACING_SERVICE_NAME: Oathkeeper
      TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL: http://jaeger:5778/sampling
      TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS: jaeger:6831
      TRACING_PROVIDERS_JAEGER_SAMPLING_TYPE: const
      TRACING_PROVIDERS_JAEGER_SAMPLING_VALUE: 1
    ports:
      - "4455:4455"
      - "4456:4456"
    volumes:
      - oathkeeper-config:/etc/config/oathkeeper
    networks:
      intranet: null

  consent:
    image: oryd/hydra-login-consent-node:v2.1.1
    restart: unless-stopped
    environment:
      HYDRA_ADMIN_URL: http://hydra:4445
    ports:
    - "3000:3000"
    networks:
      intranet: null

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
    - "4436:4436"
    - "4437:4437"
    networks:
      intranet: null

  jaeger:
    image: jaegertracing/all-in-one:1.44
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"

    networks:
      intranet: null

networks:
  intranet:
    name: ory_intranet

volumes:
  postgres-data:
  hydra-config:
    name: ory_hydra-config
    driver: local
    driver_opts:
      device: ./configs/hydra
      o: bind
      type: none
  keto-config:
    name: ory_keto-config
    driver: local
    driver_opts:
      device: ./configs/keto
      o: bind
      type: none
  kratos-config:
    name: ory_kratos-config
    driver: local
    driver_opts:
      device: ./configs/kratos/email-password
      o: bind
      type: none
  oathkeeper-config:
    name: ory_oathkeeper-config
    driver: local
    driver_opts:
      device: ./configs/oathkeeper
      o: bind
      type: none